version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    tty: true
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: kuma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kumadb
    volumes:
      - ./db/data:/var/lib/postgresql/data
networks:
  lesson:
